### ISSUE TITLE
onFinish 会多调用一次

### ISSUE THREAD

**Issue by bastengao** [BenBBear/ionic-cache-src#1]
我有两张图片，第一张图片会触发两次 onFinish 事件。貌似 onProgress 也是这样。

**Comment by BenBBear** [comment]
好， 我今晚或者明天上午看一下

**Comment by BenBBear** [comment]
仔细地debug了一下， 发现不少问题，正在解决， 不要急哈

**Comment by BenBBear** [comment]
@bastengao    我修复了不少问题， 但是没有发现callback运行多次的情况， 你可以拿https://github.com/BenBBear/ionic-cache-src-demo 当例子看一下（里面有三张图片，都没有出现多次运行的状况）

**Comment by BenBBear** [comment]
现在 version 是 0.4.1， 你可以用新的 [cache-src.js](https://raw.githubusercontent.com/BenBBear/ionic-cache-src/master/cache-src.js) 试一下

**Comment by BenBBear** [comment]
另外有一个cordova和ionic冲突的bug（可能导致 cacheSrc 下载失败）可能会出现， 见  https://github.com/driftyco/ionic-plugin-keyboard/issues/82   解决方法 stackoverflow上见这里 ： http://stackoverflow.com/questions/20890263/error-in-phonegap-application-uncaught-module-cordova-plugin-list-already-defin
