### ISSUE TITLE
this works fine in browser and ripple but not worked when app installed on device

### ISSUE THREAD

**Issue by ghostgrass** [BenBBear/ionic-cache-src#10]
this works fine in browser and ripple but not worked when app installed on device.
but change cache-src to ng-src then the image could be shown.
Any idea on this?

**Comment by ghostgrass** [comment]
now got the rootcause: if use {{}} like cache-src="{{testpic}}", then it will fail to get pic because attrs.$observe('cacheSrc', could not be excuted.
any idea on how to fix it?

**Comment by BenBBear** [comment]
Would you mind to try to install this demo app  https://github.com/BenBBear/ionic-cache-src-demo  on your testing device and see what happens? 

And the console error from chrome remote debugger will be very helpful.

**Comment by ghostgrass** [comment]
Thanks for reply.
i tried but that demo has same issue. this issue could be fixed by using scope.$watch('attrs.cacheSrc', to replace attrs.$observe('cacheSrc'. 
is there any impact from your perspective for this change?
 谢谢

**Comment by ghostgrass** [comment]
my nick name is 笨笨熊 too  :)

**Comment by BenBBear** [comment]
好奇怪，你这个问题是只在android上才发生吗？ 

我刚才在android emulator上测没问题， 另外ios有没有这个问题？

**Comment by ghostgrass** [comment]
只有安卓上有，ios上 没问题，而且只有使用{{}}绑定才有问题，直接用url没问题

**Comment by BenBBear** [comment]
自己试的时候的android是没有问题的， 而且ios成功，android失败，估计是android webview的问题了。。。 你测试的android系统version大概多少

**Comment by wahyuway** [comment]
i had problem in real android device too. Using emulator also the same problem. I use windroye as emulator. No error also from debug.

if run using ionic serve, it works well.

**Comment by BenBBear** [comment]
@wahyuway  

Awesome!  Thank you so much for the solution you brought up.   I will add this to readme.

This could be a good explanation for some not working issues about android!

However, as @ghostgrass  mentioned, using `$scope.$watch` instead of `attr.$observe` could fix some failed cases in android while both are fine in iOS. I guess there may exist angular support issues in some particular versions of webview. But I never encounter it, if more people complains, I will change it.

**Comment by trinvh2** [comment]
Hi, add preference via @wahyuway still not working.
I have 2 page, homepage and detail page. In detail page it work but homepage its not render src attribute.
I inspected on chrome, no exception occurs.

**Comment by seasonstar** [comment]
Hi, 
I encountered this issue on device in iOS 9.2, ionic 1.2.4.
And I found a solution.
Just replace 
" $ionicPlatform.ready().then(function() { "  in line 268
with
 "$ionicPlatform.ready(function() {".

Then it works perfect~

**Comment by BenBBear** [comment]
I fix the these bugs together with some else, and add video/audio support and more examples.

Thank you guys for helping!!

**Comment by King-JXN** [comment]
Maybe there is another solution, which is replace image with div by setting "src-is" to "background".
