### ISSUE TITLE
Not working with ng-repeat on a device

### ISSUE THREAD

**Issue by b0jan** [BenBBear/ionic-cache-src#13]
I tested it with multiple images using ng-repeat and it works in browser, but not on a device (Tested on iPhone, iOS9), but it works with collection-repeat on a device.

Tested on latest Ionic version 1.2.4

**Comment by BenBBear** [comment]
It should work with ng-repeat, maybe something going wrong. 

No worry, I will add some demo code for ng-repeat later.


Sorry for the late reply, so busy recent days.

**Comment by BenBBear** [comment]
I fix some bugs and add `ng-repeat` example in the demo code.  [The demo code](https://github.com/BenBBear/ionic-cache-src-demo) works fine. 


But I only test it on simulator, if problems keep still, tell me.

**Comment by mklilley** [comment]
Hi.  I found I had the same problem with ng-repeat on android device.  No longer a problem since your update. Thanks so much, this plugin is really great!

**Comment by bojanvidanovic** [comment]
Sorry for delay, it's working perfectly now. Thank you
