### ISSUE TITLE
Android bug even with <preference name="AndroidPersistentFileLocation" value="Internal" />

### ISSUE THREAD

**Issue by crouti** [BenBBear/ionic-cache-src#14]
Hi,

Thank you for your nice plugin that works perfectly on iOs and Webview, but does not load images on Android...
I tried with the recommended setting, but no chance, exactly the same.

It seems some images are loaded (but not displayed), because as i click on an area where the image should be (just a border with nothing inside), the image shows up in big size (that the normal behavior in my app). But some other don't even display this empty border and images don't seem to be 
downloaded...

No error displays...

Any idea ?
thank you very much

**Comment by crouti** [comment]
It seems the images is downloaded but never displayed on the page... strange!

**Comment by crouti** [comment]
I can see the blue progress circle go on, but a the end, nothing displays.... but no error thrown

**Comment by BenBBear** [comment]
Do you mind to share a code snippet for this problem?

Also you could use chrome remote debugger to attach to the android device, and see what the console outputs, which is very useful for debugging.

**Comment by BenBBear** [comment]
I update the example code, would you mind to download and try it?   https://github.com/BenBBear/ionic-cache-src-demo

I test it on my android emulator, it works fine.

**Comment by crouti** [comment]
Thank you very much!
i've just tried to launch the demo, followin install instructinos on your
page, and i can't luanch on android device, it says:

ionic $ ERROR running one or more of the platforms: The provided path
"/Users/utilisateur/Documents/ionic/ionic-cache-src-demo/platforms/android"
is not an Android project.
Any idea?
thanks

2016-03-05 10:34 GMT+01:00 Sayen Xinyu Zhang <notifications@github.com>:

> I update the example code, would you mind to download and try it?
> https://github.com/BenBBear/ionic-cache-src-demo
>
> I test it on my android emulator, it works fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BenBBear/ionic-cache-src/issues/14#issuecomment-192613382>
> .
>



-- 
Max UNGER
06.66.13.16.26

www.termel.fr

**Comment by crouti** [comment]
And testing with latest master from github seems to let the same problem,
works on ios, but on android:


​

2016-03-05 10:34 GMT+01:00 Sayen Xinyu Zhang <notifications@github.com>:

> I update the example code, would you mind to download and try it?
> https://github.com/BenBBear/ionic-cache-src-demo
>
> I test it on my android emulator, it works fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BenBBear/ionic-cache-src/issues/14#issuecomment-192613382>
> .
>



-- 
Max UNGER
06.66.13.16.26

www.termel.fr

**Comment by sturridge** [comment]
在Android（4.4.2和4.4.4）和iOS（9.2.1）上都没能成功使用，已经在config.xml中添加了<preference name="AndroidPersistentFileLocation" value="Internal" />

Android上运行 https://github.com/BenBBear/ionic-cache-src-demo 也没有效果，出现的现象都是：出现了空的圆形进度条，但是进度条不走，也没有替换图片，就一直保持这样。

使用Chrome的远程调试，出来的Console消息是：
`No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin. whitelist.js:24
TypeError: Cannot read property 'dataDirectory' of undefined
    at getCacheDir (file:///android_asset/www/lib/ionic-cache-src/ionic-cache-src.js:237:64)
    at fetchRemote (file:///android_asset/www/lib/ionic-cache-src/ionic-cache-src.js:268:59)
    at Object.fn (file:///android_asset/www/lib/ionic-cache-src/ionic-cache-src.js:307:64)
    at Scope.$digest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:28995:29)
    at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:29197:26
    at completeOutstandingRequest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:18706:10)
    at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:18978:7 `

**Comment by BenBBear** [comment]
我会看一下，或许系统不同，cordova提供的路径变量名有变化。



On March 22, 2016 at 8:31:16 PM, sturridge (notifications@github.com) wrote:

在Android（4.4.2和4.4.4）和iOS（9.2.1）上都没能成功使用，已经在config.xml中添加了

Android上运行 https://github.com/BenBBear/ionic-cache-src-demo 也没有效果，出现的现象都是：出现了空的圆形进度条，但是进度条不走，也没有替换图片，就一直保持这样。

使用Chrome的远程调试，出来的Console消息是：
No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin. whitelist.js:24
TypeError: Cannot read property 'dataDirectory' of undefined
at getCacheDir (file:///android_asset/www/lib/ionic-cache-src/ionic-cache-src.js:237:64)
at fetchRemote (file:///android_asset/www/lib/ionic-cache-src/ionic-cache-src.js:268:59)
at Object.fn (file:///android_asset/www/lib/ionic-cache-src/ionic-cache-src.js:307:64)
at Scope.$digest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:28995:29)
at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:29197:26
at completeOutstandingRequest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:18706:10)
at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:18978:7

**Comment by BenBBear** [comment]
@sturridge   

> TypeError: Cannot read property 'dataDirectory' of undefined

错误在这句话
```js
return $window.cordova.file.dataDirectory;
```
需要预先安装 `cordova-plugin-file`
