### ISSUE TITLE
Won't work for video tags

### ISSUE THREAD

**Issue by antonfire** [BenBBear/ionic-cache-src#15]
I can't seem to make this work for video tags, it seems to me that the code should work for HTML5 video as well as images, but no amount of fiddling seems to get it to work. Any ideas what I am doing wrong or how I can make it work with video. 

Thanks, great idea.

**Comment by BenBBear** [comment]
Be frankly I haven't tested it on video tag on device yet. I will test it later on and get back to you.

**Comment by BenBBear** [comment]
@antonfire   I fixes some problems and now it supports video tag!  

Use the newest 0.7.0 version and see the example here:   https://github.com/BenBBear/ionic-cache-src-demo/blob/master/www/index.html#L212

**Comment by antonfire** [comment]
Thanks, that's brilliant. I'm just wondering if there is anyway to make this play nice with videogular as it gives a multiple directives asking for isolate scope error

**Comment by BenBBear** [comment]
Videogular use vg-src, however this plugin set src using standard Dom setAttribute in https://github.com/BenBBear/ionic-cache-src/blob/master/ionic-cache-src.js#L224.


If two directives want to interact, that must happen in the scope I think






Saturday, March 5, 2016, 2:53 AM -0800 from notifications@github.com  <notifications@github.com>:

**Comment by BenBBear** [comment]
I will put this to my todolist.

**Comment by antonfire** [comment]
Thanks so much you're saving the day for me here, I really appreciate
