### ISSUE TITLE
Dynamic url images break in iOS.

### ISSUE THREAD

**Issue by pranavrajs** [BenBBear/ionic-cache-src#27]
I've images from S3 , when i try to cache it with the ionic-cache-src , some of the images seems to be broken. It is working fine in Android.

I'm loading the images in ng-repeat

![screen shot 2016-05-20 at 10 57 39 am](https://cloud.githubusercontent.com/assets/2246121/15418061/c6736b3a-1e79-11e6-9b84-bee95e3a1312.png)

**Comment by allupaku** [comment]
@pranavrajs - are you able to solve this issue ? could you please share the info ?

**Comment by pranavrajs** [comment]
@allupaku I could solve the issue. I was using `display:flex`. When i removed `flex`, it worked perfect ! I'm not sure about the original issue.
