### ISSUE TITLE
can we use cache-src for backround images ?

### ISSUE THREAD

**Issue by hatim-haffane** [BenBBear/ionic-cache-src#4]
how i can implement that to work with backround images ?? thanks

**Comment by BenBBear** [comment]
Sorry, it doesn't work with background images at present :<

But it's a really good suggestion, it's not gonna hard and I could work on it later.

What do you think it should be? Use a loading gif as background alternative util the download is finished? Any suggestions? : )

**Comment by BenBBear** [comment]
@hatim-haffane   love to hear your ideas :D

**Comment by hatim-haffane** [comment]
yes it will be cool if we can use the same angular-svg-round-progress on the background , or we can leave the choice to the user if we can make it as a parametr

**Comment by hatim-haffane** [comment]
i have a question for you , when i load an image using cache-src the image is not cropped to fit the div , i'm using this to load images to a slide Box so the image come with the real dimension even if i add css (width : 100% !important;) the image still shows big.
![ios simulator screen shot sep 17 2015 12 17 48](https://cloud.githubusercontent.com/assets/4057321/9931723/283be56e-5d36-11e5-9dcc-abd0c2ce2442.png)

**Comment by BenBBear** [comment]
@hatim-haffane 

`width:100% ` means your image is the same width with the container, so if your container is big then the image as well.  

Here is a working sample https://github.com/BenBBear/ionic-cache-src-demo/blob/master/www/index.html#L54

**Comment by BenBBear** [comment]
Actually this plugin has some limitation at present:

- don't support background image
- the progress circle is a `block div`, but sometime we may want it as a `inline-block`
- could not change the progress circle to other customized progress indicator


I will work on it later.

**Comment by BenBBear** [comment]
@hatim-haffane 

Now it works for background image and more, check out version [0.5.2](https://github.com/BenBBear/ionic-cache-src), and [demo](https://github.com/BenBBear/ionic-cache-src-demo)

cheers :D

**Comment by hatim-haffane** [comment]
thanks man , please can you add it to the ionic market ?? it's really cool and nice : https://market.ionic.io/

**Comment by BenBBear** [comment]
@hatim-haffane 

Wow :O  Haven't realized there is market out there, will add it soon!

**Comment by hatim-haffane** [comment]
hi can we use an animated ionic icon in place of a gif image ? that will be more elegant no ?

**Comment by BenBBear** [comment]
Certainly you can,  actually the new version expose `uiOnStart, uiOnFinish, uiOnProgress` callback, and the current loading ui is just their default implementation. 

The code is from https://github.com/BenBBear/ionic-cache-src/blob/master/ionic-cache-src.js#L34 to https://github.com/BenBBear/ionic-cache-src/blob/master/ionic-cache-src.js#L94. 

However, a loading gif is probably the easiest way in the background image case, and is not bad if you  happen to have a nice loading gif or make one yourself.

If use an animated icon, then dom manipulation is involved, and very likely you have to deal with the overlapping, margin and etc, which may be different in each cases.

**Comment by hatim-haffane** [comment]
thanks , i appreciate your help , thanks a lot

**Comment by BenBBear** [comment]
BTW you can use backgroundLoadingStyle to change the loading gif


I have admitted that it's hassle to change the uiOn* function if you only want to customize the background case....

**Comment by BenBBear** [comment]
My pleasure :-)

**Comment by hatim-haffane** [comment]
i have a use case that make me thinking of i can use this to load more than one image before dismissing the circle-progress ?

**Comment by BenBBear** [comment]
@hatim-haffane 

Do you mean each ion-slide has a image, and you want to download them at once instead of download when active?

**Comment by hatim-haffane** [comment]
yes , for me all the images start loading one after one so the slides are missed up because i see the last image at first

**Comment by BenBBear** [comment]
@hatim-haffane 

I believe this may be beyond what this plugin is about.

But you may put
```
<img cache-src="pictureurl"  style="display:none"  show-progress-circle-in-device="false">
```
into your page to trigger the download of pictureurl, so there may be a cache hit when that pictureurl slide come.

Would you mind to put a demo to show your problem?
