### ISSUE TITLE
ReferenceError: device is not defined

### ISSUE THREAD

**Issue by nadeemkhan** [BenBBear/ionic-cache-src#5]
i'm getting following issue 
![screen shot 2015-10-09 at 1 30 33 pm](https://cloud.githubusercontent.com/assets/1510017/10388739/171467d8-6e8a-11e5-9231-036a6d116c5c.png)

**Comment by BenBBear** [comment]
a little busy today >.< will look into it as soon as possible

**Comment by BenBBear** [comment]
The exception is throwed from this line:  https://github.com/BenBBear/ionic-cache-src/blob/master/ionic-cache-src.js#L206

```js
device.platform
```

The device object is only available when the "deviceready" event is fired.  But I thought it should be fine, so didn't wrap that part code inside `$ionicPlatform.ready`.  My bad... sorry 


It's an easy one and I will fix it.


Also check your project, have you installed the [cordova-plugin-device](https://github.com/apache/cordova-plugin-device)? If not

```shell
cordova plugin add cordova-plugin-device
```

**Comment by BenBBear** [comment]
Oh, wait a minute.

Actually, I wrap the code....  The exception is from L239, see following

```js
  $ionicPlatform  // the wrap
    .ready()
    .then(function() {
        var ext = '.' + attrs.cacheSrc.split('.').pop();
        var fileName = id() + ext;
        $cordovaFileTransfer
            .download(attrs.cacheSrc, getCacheDir() + fileName, {}, true)  //line 239
            .then(function() {
                cache[attrs.cacheSrc] = fileName;
                scope.uiOnFinish(scope, element, $compile, uiData);
                addSrc(getCacheDir() + fileName);
            }, scope.onError, function(progress) {
                uiData.progress = (progress.loaded / progress.total) * 100;
                scope.uiOnProgress(scope, element, $compile, uiData);
                scope.onProgress(uiData.progress);
            });
    });
```

So probably the problem is that you haven't installed the `cordova-plugin-device` plugin, so install it and try again. If problem keeps still, then let me know :)

**Comment by nadeemkhan** [comment]
wow thanks bro now it fixed :-)
