### ISSUE TITLE
collection-repeat使用时候会出现bug

### ISSUE THREAD

**Issue by match08** [BenBBear/ionic-cache-src#6]
collection-repeat使用时候会出现bug. 只要使用collection-repeat 读取缓存图片就会不对了，图片全乱了。collection-repeat使用 ion-infinite-scroll拉数据bug比较严重。单独使用ng-src不会有问题，一使用cache-src就出先图片和其他图片对调全乱了。

**Comment by BenBBear** [comment]
好， 我会尽快去仔细看一下（学期中太忙了，如果不能很及时，求理解哈 >.<）

**Comment by faceleg** [comment]
> collection-repeat use will appear when the bug. Just use collection-repeat reads the cached image will be wrong, picture the whole mess . collection-repeat using ion-infinite-scroll pull data more serious bug . Ng-src alone will not have a problem , a use cache-src on the first image and other image reversed the whole mess .

**Comment by faceleg** [comment]
> Well, I 'll go as soon as possible a closer look at the ( too busy semester , if not very timely , seeking to understand ha > . <)

**Comment by faceleg** [comment]
@match08 does `ng-repeat` have the same bug?

**Comment by johnnyoin** [comment]
@faceleg No, it works well with ng-repeat.

**Comment by BenBBear** [comment]
I add collection repeat example in the newest example: https://github.com/BenBBear/ionic-cache-src-demo.   

The only problem using with collection repeat is that ionic could not decide the height of the image. (While the order of images is correct.)


`Ng-src` seems like a special directive that gets processed earlier than common ones, so collection repeat works fine. My understanding to angular is not deep enough to make `cache-src`  be the same place, though I do try to change priority and read how `ng-src` be implemented.

A workaround is to specify the height using `collection-repeat-height`, like here: https://github.com/BenBBear/ionic-cache-src-demo/blob/master/www/index.html#L177.
