### ISSUE TITLE
Cache Expiry

### ISSUE THREAD

**Issue by dbswebsite** [BenBBear/ionic-cache-src#7]
Is there a way to set a cache expiration (don't see it, sorry)?

**Comment by BenBBear** [comment]
Currently not supported, but should be easy to add it. 

I can work on it soon, but I have too much course assignments to do now :(

**Comment by dbswebsite** [comment]
Excellent! Thx. Nice plugin.

**Comment by BenBBear** [comment]
Now expiration is support. check it out :D

**Comment by hatim-haffane** [comment]
thanks man , it cool

**Comment by dbswebsite** [comment]
Does this have the capability to work with Native Apps using Ionic
Framework?

On Tue, Oct 13, 2015 at 5:57 AM, hatim-haffane <notifications@github.com>
wrote:

> thanks man , it cool
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BenBBear/ionic-cache-src/issues/7#issuecomment-147667752>
> .
>

-- 
NOTICE: This E-mail (including attachments) is covered by the Electronic Communications 
Privacy Act, 18 U.S.C. 2510-2521, is confidential and may be legally 
privileged. If you are not the intended recipient, you are hereby notified 
that any retention, dissemination, distribution or copying of this communication 
is prohibited. Please reply to the sender that you have received the 
message in error, then delete it.

**Comment by dbswebsite** [comment]
Thanks for quick work!

**Comment by BenBBear** [comment]
my pleasure :)
