### ISSUE TITLE
Doesn't Run on Device

### ISSUE THREAD

**Issue by dbswebsite** [BenBBear/ionic-cache-src#8]
Works fine as 'ionic serve -l', but same code shows no images at all when loaded on a real device (Android Nexus 6).

**Comment by BenBBear** [comment]
I only test in device using `ionic run ios` 

Is it possible for you to try running this command and tell me the result?(need a mac)  If `ionic run ios` works but android nexus 6 doesn't, then may help me to narrow down the problem.

**Comment by BenBBear** [comment]
And be careful the ios9 security policy, you may have to change the `.plist` file 
https://github.com/BenBBear/ionic-cache-src#ios-9-nsapptransportsecurity

**Comment by dbswebsite** [comment]
I only have an ipad mini in my immediate possession, and seems to work fine there. Thanks.

**Comment by BenBBear** [comment]
then it could be some problems specific with android, I will look into it later

**Comment by dbswebsite** [comment]
Its the same problem on Galaxy Note 3, fyi.

**Comment by BenBBear** [comment]
Hi, here is a demo of this plugin https://github.com/BenBBear/ionic-cache-src-demo

Follow the readme commands, and it works well in my android Genymotion simulator. 

Would you mind to clone that repo and try to run it?  Later I will try to run on a real Android device.

**Comment by dbswebsite** [comment]
The demo seems to work fine. I see all images.

I did try with the original code to reinstall all cordova plugins, but still don't see images.

**Comment by BenBBear** [comment]
How do you debug your code?  

You could use Safari and Chrome remote debugging to inspect and step debugging your code, also see all the console outputs. Then you could know where the exception is.

Links: 

- http://moduscreate.com/enable-remote-web-inspector-in-ios-6/
- https://developer.chrome.com/devtools/docs/remote-debugging

**Comment by dbswebsite** [comment]
I use chrome with android. I already looked at it via Dev Tools. There are no exceptions at all. The network tab shows no imgs loaded, and no 404's. When I inspect the element I see:

...
<img class="drinkImage" cache-src="http://admin.example.com/72\1043_57 Chassis.jpg" expiration="604800">
...

If I change cache-src to src, the image loads (the url is correct). 

Thanks. Could I be missing a plugin???

**Comment by dbswebsite** [comment]
Sorry, image tag is:

<img class="drinkImage" cache-src="http://admin.abmcocktails.com/72\1043_57 Chassis.jpg" expiration="604800">

**Comment by dbswebsite** [comment]
That's the thing, there aren't any errors or exceptions popping up.

On Fri, Oct 16, 2015 at 4:41 PM, Xinyu Zhang <notifications@github.com>
wrote:

> How do you debug your code?
>
> You could use Safari and Chrome remote debugging to inspect and step
> debugging your code, also see all the console outputs. Then you could know
> where the exception is.
>
> Links:
>
>    - http://moduscreate.com/enable-remote-web-inspector-in-ios-6/
>    - https://developer.chrome.com/devtools/docs/remote-debugging
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BenBBear/ionic-cache-src/issues/8#issuecomment-148828797>
> .
>

-- 
NOTICE: This E-mail (including attachments) is covered by the Electronic Communications 
Privacy Act, 18 U.S.C. 2510-2521, is confidential and may be legally 
privileged. If you are not the intended recipient, you are hereby notified 
that any retention, dissemination, distribution or copying of this communication 
is prohibited. Please reply to the sender that you have received the 
message in error, then delete it.

**Comment by BenBBear** [comment]
No exception, no image and nothing happens, wield.  Just to check that I understand the situation:

- In browser, works
- In iOS, works 
- In Android, no images and exceptions

Does the above describe your problem?

Because it looks like the angular module is not loaded(which I have done several times before), make sure that you have 

```js
angular.module('myApp', ['ionic','ionic-cache-src'])
```

However, if the iOS and browser work, then the module is loaded.... Then it could be a strange thing happened.

BTW it's `expire`.

**Comment by dbswebsite** [comment]
I have that module included in the code, and it turns out that it is
happening in the iOS. I guess that it must've skipped that part when
building that one time or something, because it's no longer coming up.

On Fri, Oct 16, 2015 at 6:06 PM, Xinyu Zhang <notifications@github.com>
wrote:

> No exception, no image and nothing happens, wield. Just to check that I
> understand the situation:
>
>    - In browser, works
>    - In iOS, works
>    - In Android, no images and exceptions
>
> Does the above describe your problem?
>
> Because it looks like the angular module is not loaded(which I have done
> several times before), make sure that you have
>
> angular.module('myApp', ['ionic','ionic-cache-src'])
>
> However, if the iOS and browser work, then the module is loaded.... Then
> it could be a strange thing happened.
>
> BTW it's expire.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BenBBear/ionic-cache-src/issues/8#issuecomment-148847297>
> .
>

-- 
NOTICE: This E-mail (including attachments) is covered by the Electronic Communications 
Privacy Act, 18 U.S.C. 2510-2521, is confidential and may be legally 
privileged. If you are not the intended recipient, you are hereby notified 
that any retention, dissemination, distribution or copying of this communication 
is prohibited. Please reply to the sender that you have received the 
message in error, then delete it.

**Comment by dbswebsite** [comment]
Sorry, I need to change the details. I did indeed say it worked on iOS. The
images loaded when I tested it, but I just retried, and they are not
loading today. I think possibly previously there was other short term
caching (maybe Angular). So there are now no images at all for me on iOS or
Android, and no exceptions either.

Images do load in the browser though with 'ionic serve -l'. But every time
the screen loads, the images show the loading animation as if its the first
time the image is being loaded. Also, inspecting the browser's
localStorage, there is nothing related there (is this where the cache is?).

angular.module('myApp', ['ionic','ionic-cache-src']) is the first line in
app.js. Does the location of this statement make any difference?

I tried re-installing this plugin, and that did not change anything.



On Fri, Oct 16, 2015 at 6:06 PM, Xinyu Zhang <notifications@github.com>
wrote:

> No exception, no image and nothing happens, wield. Just to check that I
> understand the situation:
>
>    - In browser, works
>    - In iOS, works
>    - In Android, no images and exceptions
>
> Does the above describe your problem?
>
> Because it looks like the angular module is not loaded(which I have done
> several times before), make sure that you have
>
> angular.module('myApp', ['ionic','ionic-cache-src'])
>
> However, if the iOS and browser work, then the module is loaded.... Then
> it could be a strange thing happened.
>
> BTW it's expire.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BenBBear/ionic-cache-src/issues/8#issuecomment-148847297>
> .
>



-- 
Hal Burgiss
CTO and DevOps
*DBS**>Interactive* <http://www.dbswebsite.com/>

-- 
NOTICE: This E-mail (including attachments) is covered by the Electronic Communications 
Privacy Act, 18 U.S.C. 2510-2521, is confidential and may be legally 
privileged. If you are not the intended recipient, you are hereby notified 
that any retention, dissemination, distribution or copying of this communication 
is prohibited. Please reply to the sender that you have received the 
message in error, then delete it.

**Comment by ghostgrass** [comment]
now got the rootcause: if use {{}} like cache-src="{{testpic}}", then it will fail to get pic because attrs.$observe('cacheSrc', could not be excuted.
any idea on how to fix it?

**Comment by ikrong** [comment]
我也有也遇到了 【ghostgrass】 这样的问题，{{}} 之间的链接无法显示出图片来，不知道什么原因~>.<~

**Comment by dbswebsite** [comment]
I'm having the same problem, too.

2015-12-10 1:48 GMT-05:00 krong <notifications@github.com>:

> 我也有也遇到了 【ghostgrass】 这样的问题，{{}} 之间的链接无法显示出图片来，不知道什么原因~>.<~
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BenBBear/ionic-cache-src/issues/8#issuecomment-163517369>
> .
>

-- 
NOTICE: This E-mail (including attachments) is covered by the Electronic Communications 
Privacy Act, 18 U.S.C. 2510-2521, is confidential and may be legally 
privileged. If you are not the intended recipient, you are hereby notified 
that any retention, dissemination, distribution or copying of this communication 
is prohibited. Please reply to the sender that you have received the 
message in error, then delete it.

**Comment by judezhu** [comment]
I have the same issue here. I have {{}} in my image url as well.

**Comment by BenBBear** [comment]
I fix this together with some other bugs and add video/audio tag support in 0.7.0.  Thanks a lot for helping to spot and fix the issues!
